#include "LDM_Common.idl"

module P_NSTEL
{
    enum T_OperationModeType
    {
        L_OperationModeType_NORMAL,
        L_OperationModeType_EMERGENCY,
        L_OperationModeType_MANUAL
    };

    enum T_PalmModeType
    {
        L_PalmModeType_ON,
        L_PalmModeType_OFF
    };

    enum T_TargetFixType
    {
        L_TargetFixType_FIXED,
        L_TargetFixType_ETC
    };

    enum T_ArmPositionType
    {
        L_ArmPositionType_RELEASE,
        L_ArmPositionType_DRIVING
    };

    enum T_CannonRestoreType
    {
        L_CannonRestoreType_RELEASE,
        L_CannonRestoreType_RESTORE
    };

    enum T_CannonFixType
    {
        L_CannonFixType_RELEASE,
        L_CannonFixType_FIX
    };

    enum T_EquipOpenStatusType
    {
        L_EquipOpenStatusType_CLOSE,
        L_EquipOpenStatusType_OPEN
    };

    enum T_CannonFixStatusType
    {
        L_CannonFixStatusType_NORMAL,
        L_CannonFixStatusType_FIXED
    };

    enum T_DeckClearanceType
    {
        L_DeckClearanceType_OUT_OF_DECK,
        L_DeckClearanceType_IN_DECK
    };

    enum T_CannonDrivingType
    {
        L_CannonDrivingType_DRIVING,
        L_CannonDrivingType_DONE
    };

    enum T_CannonLockType
    {
        L_CannonLockType_NORMAL,
        L_CannonLockType_LOCKED
    };

    enum T_ShutdownType
    {
        L_ShutdownType_UNKNOWN,
        L_ShutdownType_SHUTDOWN
    };

    enum T_EnergyStorageStatusType
    {
        L_EnergyStorageStatusType_NORMAL,
        L_EnergyStorageStatusType_DISCHARGE
    };

    enum T_BITResultType
    {
        L_BITResultType_NORMAL,
        L_BITResultType_ABNORMAL
    };

    struct C_CannonDrivingDevice
    {
        P_LDM_Common::T_IdentifierType	A_sourceID;
        P_LDM_Common::T_DateTimeType	A_timeOfDataGeneration;
        P_LDM_Common::T_IdentifierType	A_specification_sourceID;
    };

    struct C_CannonDrivingDevice_Specification
    {
        P_LDM_Common::T_IdentifierType	A_sourceID;
        P_LDM_Common::T_DateTimeType	A_timeOfDataGeneration;
        P_LDM_Common::T_Boolean	A_powerOnBITSupported;
        P_LDM_Common::T_Boolean	A_continousBITSupported;
        P_LDM_Common::T_Boolean	A_initiatedBITSupported;
        P_LDM_Common::T_Int32	A_continousBITInterval;
        sequence <P_LDM_Common::T_IdentifierType>	A_specifiedCannonDrivingDevices_sourceID;
    };


    struct C_CannonDrivingDevice_commandDriving
    {
        P_LDM_Common::T_IdentifierType	A_sourceID;
        P_LDM_Common::T_IdentifierType	A_recepientID;
        P_LDM_Common::T_DateTimeType	A_timeOfDataGeneration;
        P_LDM_Common::T_Int32	A_referenceNum;
        P_LDM_Common::T_Double	A_roundPosition;
        P_LDM_Common::T_Double	A_upDownPosition;
        P_LDM_Common::T_Double	A_roundAngleVelocity;
        P_LDM_Common::T_Double	A_upDownAngleVelocity;
        P_LDM_Common::T_Double	A_cannonUpDownAngle;
        P_LDM_Common::T_Double	A_topRelativeAngle;
        T_OperationModeType	A_operationMode;
        T_PalmModeType	A_parm;
        T_TargetFixType	A_targetFix;
        T_ArmPositionType	A_autoArmPosition;
        T_ArmPositionType	A_manualArmPosition;
        T_CannonRestoreType	A_mainCannonRestore;
        T_CannonFixType	A_mainCannonFix;
        T_EquipOpenStatusType	A_closureEquipOpenStatus;
    };

    struct C_CannonDrivingDevice_Signal
    {
        P_LDM_Common::T_IdentifierType	A_sourceID;
        P_LDM_Common::T_IdentifierType	A_recepientID;
        P_LDM_Common::T_DateTimeType	A_timeOfDataGeneration;
        P_LDM_Common::T_Double	A_azAngleVelocity;
        P_LDM_Common::T_Double	A_e1AngleVelocity;
        T_EnergyStorageStatusType	A_energyStorage;
        T_CannonFixType	A_mainCannonFixStatus;
        T_DeckClearanceType	A_deckCleance;
        T_CannonDrivingType	A_autoArmPositionComplement;
        T_CannonDrivingType	A_manualArmPositionComplement;
        T_CannonDrivingType	A_mainCannonRestoreComplement;
        T_CannonLockType	A_armSafetyMainCannonLock;
        T_ShutdownType	A_shutdown;
        P_LDM_Common::T_Double	A_roundGyro;
        P_LDM_Common::T_Double	A_upDownGyro;
    };

    struct C_VehicleSpeed{
        P_LDM_Common::T_IdentifierType	A_sourceID;
        P_LDM_Common::T_DateTimeType	A_timeOfDataGeneration;
        P_LDM_Common::T_Double	A_value;
    };

    struct C_CannonDrivingDevice_PowerOnBIT {
        P_LDM_Common::T_IdentifierType	A_sourceID;
        P_LDM_Common::T_DateTimeType	A_timeOfDataGeneration;
        P_LDM_Common::T_IdentifierType	A_cannonDrivingDevice_sourceID;
        P_LDM_Common::T_Boolean	A_BITRunning;
        T_BITResultType	A_upDownMotor;
        T_BITResultType	A_roundMotor;
        T_BITResultType	A_upDownAmp;
        T_BITResultType	A_roundAmp;
        T_BITResultType	A_baseGyro;
        T_BITResultType	A_topForwardGryro;
        T_BITResultType	A_vehicleForwardGyro;
        T_BITResultType	A_powerController;
        T_BITResultType	A_energyStorage;
        T_BITResultType	A_directPower;
        T_BITResultType	A_cableLoop;
    };

    struct C_CannonDrivingDevice_PBIT{
        P_LDM_Common::T_IdentifierType	A_sourceID;
        P_LDM_Common::T_DateTimeType	A_timeOfDataGeneration;
        P_LDM_Common::T_IdentifierType	A_cannonDrivingDevice_sourceID;
        T_BITResultType	A_upDownMotor;
        T_BITResultType	A_roundMotor;
        T_BITResultType	A_upDownAmp;
        T_BITResultType	A_roundAmp;
        T_BITResultType	A_baseGyro;
        T_BITResultType	A_topForwardGryro;
        T_BITResultType	A_vehicleForwardGyro;
        T_BITResultType	A_powerController;
        T_BITResultType	A_energyStorage;
        T_BITResultType	A_directPower;
        T_BITResultType	A_cableLoop;
        T_BITResultType	A_upDownPark;
        T_BITResultType	A_roundPark;
        T_BITResultType	A_mainCannonLock;
        T_BITResultType	A_controllerNetwork;
    };

    struct C_CannonDrivingDevice_IBIT{
        P_LDM_Common::T_IdentifierType	A_sourceID;
        P_LDM_Common::T_DateTimeType	A_timeOfDataGeneration;
        P_LDM_Common::T_IdentifierType	A_cannonDrivingDevice_sourceID;
        P_LDM_Common::T_Boolean	A_BITRunning;
        T_BITResultType	A_upDownMotor;
        T_BITResultType	A_roundMotor;
        T_BITResultType	A_upDownAmp;
        T_BITResultType	A_roundAmp;
        T_BITResultType	A_baseGyro;
        T_BITResultType	A_topForwardGryro;
        T_BITResultType	A_vehicleForwardGyro;
        T_BITResultType	A_powerController;
        T_BITResultType	A_energyStorage;
        T_BITResultType	A_directPower;
        T_BITResultType	A_cableLoop;
    };
};

