#include "LDM_Common.idl"
#include "UCMS_PSM.idl"

module P_NSTEL
{
    typedef float T_Float;

    enum T_OperationModeType
    {
        L_OperationModeType_NORMAL,
        L_OperationModeType_EMERGENCY,
        L_OperationModeType_MANUAL
    };

    enum T_OnOffType
    {
        L_OnOffType_ON,
        L_OnOffType_OFF
    };

    enum T_TargetAllotType
    {
        L_TargetAllotType_ALLOT,
        L_TargetAllotType_ETC
    };

    enum T_ArmPositionLockType
    {
        L_ArmPositionLockType_RELEASE,
        L_ArmPositionLockType_LOCK
    };

    enum T_MainCannonReturnType
    {
        L_MainCannonReturnType_RELEASE,
        L_MainCannonReturnType_COMMAND
    };

    enum T_MainCannonFixType
    {
        L_MainCannonFixType_RELEASE,
        L_MainCannonFixType_COMMAND
    };

    enum T_MainCannonFixStatusType
    {
        L_MainCannonFixStatusType_NORMAL,
        L_MainCannonFixStatusType_FIX
    };

    enum T_MainCannonReturnStatusType
    {
        L_MainCannonReturnStatusType_RUNNING,
        L_MainCannonReturnStatusType_COMPLETE
    };

    enum T_ArmSafetyMainCannonLock
    {
        L_ArmSafetyMainCannonLock_NORMAL,
        L_ArmSafetyMainCannonLock_COMPLETE
    };

    enum T_EquipOpenLockType
    {
        L_EquipOpenLockType_LOCK,
        L_EquipOpenLockType_OPEN
    };

    enum T_ChangingStatusType
    {
        L_ChangingStatusType_NORMAL,
        L_ChangingStatusType_DISCHARGE
    };

    enum T_DekClearanceType
    {
        L_DekClearanceType_OUTSIDE,
        L_DekClearanceType_RUNNING
    };

    enum T_ArmPositionType
    {
        L_ArmPositionType_NORMAL,
        L_ArmPositionType_MANUAL
    };

    enum T_CannonDrivingDeviceShutdownType
    {
        L_CannonDrivingDeviceShutdownType_UNKNOWN,
        L_CannonDrivingDeviceShutdownType_SHUTDOWN
    };

    struct C_Cannon_Driving_Device_resultBIT {
        P_LDM_Common::T_IdentifierType	A_sourceID;
        P_LDM_Common::T_DateTimeType	A_timeOfDataGeneration;
        P_LDM_Common::T_Int32	A_referenceNum;
        P_LDM_Common::T_IdentifierType	A_runBITEntity_sourceID;
        P_UCMS::T_BITType	A_type;
        P_LDM_Common::T_Boolean	A_BITRunning;
        P_LDM_Common::T_Boolean	A_upDownMotor;
        P_LDM_Common::T_Boolean	A_roundMotor;
        P_LDM_Common::T_Boolean	A_upDownAmp;
        P_LDM_Common::T_Boolean	A_roundAmp;
        P_LDM_Common::T_Boolean	A_baseGyro;
        P_LDM_Common::T_Boolean	A_topForwardGryro;
        P_LDM_Common::T_Boolean	A_vehicleForwardGyro;
        P_LDM_Common::T_Boolean	A_power_Controller;
        P_LDM_Common::T_Boolean	A_energyStorage;
        P_LDM_Common::T_Boolean	A_directPower;
        P_LDM_Common::T_Boolean	A_cableLoop;
    };

    struct C_Cannon_Driving_Device_CBIT{
        P_LDM_Common::T_IdentifierType	A_sourceID;
        P_LDM_Common::T_DateTimeType	A_timeOfDataGeneration;
        P_LDM_Common::T_IdentifierType	A_runBITEntity_sourceID;
        P_UCMS::T_BITType	A_type;
        P_LDM_Common::T_Boolean	A_upDownMotor;
        P_LDM_Common::T_Boolean	A_roundMotor;
        P_LDM_Common::T_Boolean	A_upDownAmp;
        P_LDM_Common::T_Boolean	A_roundAmp;
        P_LDM_Common::T_Boolean	A_baseGyro;
        P_LDM_Common::T_Boolean	A_topForwardGryro;
        P_LDM_Common::T_Boolean	A_vehicleForwardGyro;
        P_LDM_Common::T_Boolean	A_powerController;
        P_LDM_Common::T_Boolean	A_energyStorage;
        P_LDM_Common::T_Boolean	A_directPower;
        P_LDM_Common::T_Boolean	A_cableLoop;
        P_LDM_Common::T_Boolean	A_upDownPark;
        P_LDM_Common::T_Boolean	A_round_Park;
        P_LDM_Common::T_Boolean	A_mainCannon_Lock;
        P_LDM_Common::T_Boolean	A_commFault;
    };

    struct C_Cannon_Driving_Device_PBIT{
        P_LDM_Common::T_IdentifierType	A_sourceID;
        P_LDM_Common::T_DateTimeType	A_timeOfDataGeneration;
        P_LDM_Common::T_IdentifierType	A_runBITEntity_sourceID;
        P_UCMS::T_BITType	A_type;
        P_LDM_Common::T_Boolean	A_BITRunning;
        P_LDM_Common::T_Boolean	A_upDownMotor;
        P_LDM_Common::T_Boolean	A_roundMotor;
        P_LDM_Common::T_Boolean	A_upDownAmp;
        P_LDM_Common::T_Boolean	A_roundAmp;
        P_LDM_Common::T_Boolean	A_baseGyro;
        P_LDM_Common::T_Boolean	A_topForwardGryro;
        P_LDM_Common::T_Boolean	A_vehicleForwardGyroi;
        P_LDM_Common::T_Boolean	A_powerController;
        P_LDM_Common::T_Boolean	A_energyStorage;
        P_LDM_Common::T_Boolean	A_directPower;
        P_LDM_Common::T_Boolean	A_cableLoop;
    };

    struct C_Vehicle_Speed{
        P_LDM_Common::T_IdentifierType A_sourceID;
        P_LDM_Common::T_DateTimeType A_timeOfDataGeneration;
        P_LDM_Common::T_SpeedInMetresPerSecType A_speed;
    };

    struct C_Cannon_Actuator_Control
    {
        P_LDM_Common::T_IdentifierType	A_recipientID;
        P_LDM_Common::T_IdentifierType	A_sourceID;
        P_LDM_Common::T_DateTimeType	A_timeOfDataGeneration;
        P_NSTEL::T_Float	A_drivingPosition;
        P_NSTEL::T_Float	A_upDownPosition;
        P_NSTEL::T_Float	A_roundAngleVelocity;
        P_NSTEL::T_Float	A_upDownAngleVelocity;
        P_NSTEL::T_Float	A_cannonUpDownAngle;
        P_NSTEL::T_Float	A_topRelativeAngle;
        P_NSTEL::T_OperationModeType	A_operationMode;
        P_NSTEL::T_OnOffType	A_parm;
        P_NSTEL::T_TargetAllotType	A_targetDesingation;
        P_NSTEL::T_ArmPositionLockType	A_autoArmPosition;
        P_NSTEL::T_ArmPositionLockType	A_manualArmPosition;
        P_NSTEL::T_MainCannonReturnType	A_mainCannonRestore;
        P_NSTEL::T_MainCannonFixType	A_manCannonFix;
        P_NSTEL::T_EquipOpenLockType	A_closeEquipOpenStatus;
    };

    struct C_Cannon_Actuator_Signal
    {
        P_LDM_Common::T_IdentifierType	A_recipientID;
        P_LDM_Common::T_IdentifierType	A_sourceID ;
        P_LDM_Common::T_DateTimeType	A_timeOfDataGeneration;
        P_NSTEL::T_Float	A_azAngle;
        P_NSTEL::T_Float	A_e1AngleVelocity;
        P_NSTEL::T_ChangingStatusType	A_energyStorage;
        P_NSTEL::T_MainCannonFixStatusType	A_mainCannonFixStatus;
        P_NSTEL::T_DekClearanceType	A_deckClearance;
        P_NSTEL::T_ArmPositionType	A_autoArmPositionComplement;
        P_NSTEL::T_ArmPositionType	A_manualArmPositionComple;
        P_NSTEL::T_MainCannonReturnStatusType	A_mainCannonRestoreComplement;
        P_NSTEL::T_ArmSafetyMainCannonLock	A_armSafetyMainCannonLock;
        P_NSTEL::T_CannonDrivingDeviceShutdownType	A_shutdown;
        P_NSTEL::T_Float	A_roundGyro;
        P_NSTEL::T_Float	A_upDownGyro;
    };
};
